"""init schema

Revision ID: c1590d74fa04
Revises: e0d5ed60f30d
Create Date: 2026-04-16 03:59:38.798665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1590d74fa04'
down_revision: Union[str, Sequence[str], None] = 'e0d5ed60f30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargas_id'), 'cargas', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'error', name='job_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_cache',
    sa.Column('hash', sa.CHAR(length=64), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_process_cache_hash'), 'process_cache', ['hash'], unique=False)
    op.create_table('rotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('coord', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_rotas_id'), 'rotas', ['id'], unique=False)
    op.create_table('rota_cargas',
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rota_id'], ['rotas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rota_id', 'carga_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rota_cargas')
    op.drop_index(op.f('ix_rotas_id'), table_name='rotas')
    op.drop_table('rotas')
    op.drop_index(op.f('ix_process_cache_hash'), table_name='process_cache')
    op.drop_table('process_cache')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_cargas_id'), table_name='cargas')
    op.drop_table('cargas')
    # ### end Alembic commands ###
