version: '3'

tasks:
  reset-api:
    desc: Reset the API
    cmds:
      - echo "Resetting the API..."
      - docker-compose -f neoroute_api/docker-compose.yml up -d
      - echo "Resetting the database..."
      - docker-compose -f neoroute_api/docker-compose.yml down -v
      - docker-compose -f neoroute_api/docker-compose.yml up -d
      - echo "Running API..."
      - PYTHONPATH=./neoroute_api .venv/bin/uvicorn app.main:app --reload
      - echo "API reset complete!"
  start-api:
    desc: Start the API
    cmds:
      - echo "Starting the API..."
      - docker-compose -f neoroute_api/docker-compose.yml up -d
      - PYTHONPATH=./neoroute_api .venv/bin/uvicorn app.main:app --reload
      - echo "API started!"

